const fs = require('fs');
const path = require('path');

class FridayDocumentService {
  constructor() {
    this.outputDir = path.resolve(__dirname, '../../uploads/friday_documents');
    this.ensureDirectoryExists();
  }

  ensureDirectoryExists() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate different formats based on input
   * @param {string} docType - 'pdf' | 'word' | 'excel' | 'markdown' | 'text' | 'code'
   * @param {string} title - Title of document
   * @param {string} content - Text content or structured data
   */
  async generateDocument(docType, title, content) {
    this.ensureDirectoryExists();
    const cleanTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '_');
    let fileName = '';
    let fileContent = '';

    switch (docType.toLowerCase()) {
      case 'excel':
      case 'spreadsheet':
        fileName = `${cleanTitle}_sheet.csv`;
        fileContent = this.formatAsCSV(content);
        break;

      case 'word':
      case 'doc':
        fileName = `${cleanTitle}_doc.doc`; // HTML format readable natively by MS Word
        fileContent = `
          <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
          <head><title>${title}</title><style>body { font-family: Arial, sans-serif; line-height: 1.6; }</style></head>
          <body>
            <h1>${title}</h1>
            <p>${content.replace(/\n/g, '<br/>')}</p>
          </body>
          </html>
        `;
        break;

      case 'markdown':
      case 'md':
        fileName = `${cleanTitle}_notes.md`;
        fileContent = `# ${title}\n\n${content}`;
        break;

      case 'pdf':
        fileName = `${cleanTitle}_document.pdf`;
        // Since compiling PDF binaries requires heavy libraries, we write a structured HTML report
        // which can be printed/saved as PDF in the browser, or write clean postscript/pdf indicators.
        fileContent = `%PDF-1.4\n1 0 obj\n<< /Title (${title}) /Creator (FRIDAY Voice Assistant) >>\nendobj\nxref\n0 0\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n\n[Alternative View: Printable Document Content]\nTitle: ${title}\n\n${content}`;
        break;

      case 'code':
        fileName = `${cleanTitle}_code.js`;
        fileContent = `// Generated by FRIDAY Voice Assistant\n// Title: ${title}\n\n${content}`;
        break;

      default:
        fileName = `${cleanTitle}_text.txt`;
        fileContent = `Title: ${title}\n\n${content}`;
    }

    const filePath = path.join(this.outputDir, fileName);
    await fs.promises.writeFile(filePath, fileContent, 'utf8');

    return {
      fileName,
      filePath,
      docType,
      sizeBytes: fileContent.length
    };
  }

  formatAsCSV(data) {
    if (typeof data === 'string') {
      // If it's already comma separated or multi-line
      if (data.includes(',') || data.includes('\n')) return data;
      // Wrap words
      return data.split(' ').map(word => `"${word}"`).join(',');
    }
    if (Array.isArray(data)) {
      return data.map(row => {
        if (Array.isArray(row)) {
          return row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',');
        }
        return `"${String(row).replace(/"/g, '""')}"`;
      }).join('\n');
    }
    return `Content,Timestamp\n"${String(data)}","${new Date().toISOString()}"`;
  }
}

module.exports = new FridayDocumentService();
